-- Wedding invitation (GitHub Pages + Supabase)
-- Run this script in Supabase SQL Editor.

create extension if not exists pgcrypto;

-- RSVP ----------------------------------------------------------------------
create table if not exists public.rsvp_entries (
  id bigint generated by default as identity primary key,
  which_side text not null,
  can_attend text not null,
  guest_name text not null,
  phone_number text not null default '',
  companion_count integer not null default 1,
  meal_attendance text not null default '',
  created_at timestamptz not null default now()
);

alter table public.rsvp_entries enable row level security;

revoke all on table public.rsvp_entries from anon, authenticated;
grant insert on table public.rsvp_entries to anon, authenticated;
grant usage, select on sequence public.rsvp_entries_id_seq to anon, authenticated;

drop policy if exists "anon_insert_rsvp" on public.rsvp_entries;
create policy "anon_insert_rsvp"
  on public.rsvp_entries
  for insert
  to anon, authenticated
  with check (true);

-- Guestbook -----------------------------------------------------------------
create table if not exists public.guestbook_entries (
  id bigint generated by default as identity primary key,
  name text not null,
  message text not null,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.guestbook_entries enable row level security;

revoke all on table public.guestbook_entries from anon, authenticated;

create or replace view public.guestbook_public_entries
with (security_invoker = false) as
select id, name, message, created_at
from public.guestbook_entries
order by created_at desc;

grant select on public.guestbook_public_entries to anon, authenticated;

create or replace function public.guestbook_create(name text, message text, password_plain text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
begin
  if length(trim(coalesce(name, ''))) = 0 then
    return jsonb_build_object('success', false, 'error', '이름을 입력해주세요.');
  end if;

  if length(trim(coalesce(message, ''))) = 0 then
    return jsonb_build_object('success', false, 'error', '메시지를 입력해주세요.');
  end if;

  if length(coalesce(password_plain, '')) < 4 then
    return jsonb_build_object('success', false, 'error', '비밀번호는 4자 이상이어야 합니다.');
  end if;

  insert into public.guestbook_entries (name, message, password_hash)
  values (trim(name), trim(message), encode(digest(password_plain, 'sha256'), 'hex'))
  returning id into v_id;

  return jsonb_build_object('success', true, 'id', v_id);
end;
$$;

create or replace function public.guestbook_verify(entry_id bigint, password_plain text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry public.guestbook_entries%rowtype;
  v_hash text;
begin
  select * into v_entry
  from public.guestbook_entries
  where id = entry_id;

  if not found then
    return jsonb_build_object('success', false, 'error', '해당 메시지를 찾을 수 없습니다.');
  end if;

  v_hash := encode(digest(coalesce(password_plain, ''), 'sha256'), 'hex');

  if v_entry.password_hash != v_hash then
    return jsonb_build_object('success', false, 'error', '비밀번호가 일치하지 않습니다.');
  end if;

  return jsonb_build_object(
    'success', true,
    'data', jsonb_build_object(
      'id', v_entry.id,
      'name', v_entry.name,
      'message', v_entry.message
    )
  );
end;
$$;

create or replace function public.guestbook_update(entry_id bigint, name text, message text, password_plain text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry public.guestbook_entries%rowtype;
  v_hash text;
begin
  select * into v_entry
  from public.guestbook_entries
  where id = entry_id;

  if not found then
    return jsonb_build_object('success', false, 'error', '해당 메시지를 찾을 수 없습니다.');
  end if;

  v_hash := encode(digest(coalesce(password_plain, ''), 'sha256'), 'hex');

  if v_entry.password_hash != v_hash then
    return jsonb_build_object('success', false, 'error', '비밀번호가 일치하지 않습니다.');
  end if;

  if length(trim(coalesce(name, ''))) = 0 then
    return jsonb_build_object('success', false, 'error', '이름을 입력해주세요.');
  end if;

  if length(trim(coalesce(message, ''))) = 0 then
    return jsonb_build_object('success', false, 'error', '메시지를 입력해주세요.');
  end if;

  update public.guestbook_entries
  set
    name = trim(guestbook_update.name),
    message = trim(guestbook_update.message),
    updated_at = now()
  where id = entry_id;

  return jsonb_build_object('success', true);
end;
$$;

create or replace function public.guestbook_delete(entry_id bigint, password_plain text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_entry public.guestbook_entries%rowtype;
  v_hash text;
begin
  select * into v_entry
  from public.guestbook_entries
  where id = entry_id;

  if not found then
    return jsonb_build_object('success', false, 'error', '해당 메시지를 찾을 수 없습니다.');
  end if;

  v_hash := encode(digest(coalesce(password_plain, ''), 'sha256'), 'hex');

  if v_entry.password_hash != v_hash then
    return jsonb_build_object('success', false, 'error', '비밀번호가 일치하지 않습니다.');
  end if;

  delete from public.guestbook_entries where id = entry_id;

  return jsonb_build_object('success', true);
end;
$$;

revoke all on function public.guestbook_create(text, text, text) from public;
revoke all on function public.guestbook_verify(bigint, text) from public;
revoke all on function public.guestbook_update(bigint, text, text, text) from public;
revoke all on function public.guestbook_delete(bigint, text) from public;

grant execute on function public.guestbook_create(text, text, text) to anon, authenticated;
grant execute on function public.guestbook_verify(bigint, text) to anon, authenticated;
grant execute on function public.guestbook_update(bigint, text, text, text) to anon, authenticated;
grant execute on function public.guestbook_delete(bigint, text) to anon, authenticated;
